<?php

/**
 * @file
 * Install file for Todo List Content Type module
 */

/**
 * Implements hook_install().
 */
function todos_install() {
  $t = get_t();
  node_types_rebuild();
  $types = node_type_get_types();
  // Add a body field and set the body label
  node_add_body_field($types['todo_list'], $t('Description'));
  $body_instance = field_info_instance('node', 'body', 'todo_list');
  $body_instance['type'] = 'text_summary_or_trimmed';
  field_update_instance($body_instance);
}
